version: "3"

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28

services:
  #nginx
  nginx:
    build:
      context: docker/nginx
    ports:
      - "8080:80"
#      - "443:443"
    volumes:
      - ./src:/var/www
      - ./nginx_logs:/var/log/nginx
    links:
      - php_fpm
    networks:
      - internal
  #php
  php_fpm:
    build:
      context: docker/php_fpm
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./src:/var/www
      - ./composer:/.composer
    networks:
      - internal
  #database
  mariadb:
    build:
      context: docker/mariadb
    volumes:
      - ./db/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: xuburuFantik@1212
    ports:
      - 8081:3306
    networks:
      - internal
  #database control
#  phpmyadmin:
#    build:
#      context: docker/phpmyadmin
#    links:
#      - mariadb:db
#    ports:
#      - 8082:80
#    environment:
#      MYSQL_ROOT_PASSWORD: qwerty
#    depends_on:
#      - mariadb
#    networks:
#      - internal
